import { defineConfig } from 'orval';

export default defineConfig({
  schema: {
    output: {
      schemas: './src/api',
      override: {
        header: ({ title, description, version }) => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(title ? [title] : []),
          ...(description ? [description] : []),
          ...(version ? [`OpenAPI spec version: ${version}`] : []),
          'eslint-disable',
        ],
      },
    },
    input: {
      target: `schema.yaml`,
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
});
