openapi: 3.1.0
info:
  title: Flow - OpenAPI 1.0
  termsOfService: http://swagger.io/terms/
  version: 0.0.1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://flow.com/api
tags:
  - name: user
    description: Operations related to users
paths:
  /login:
    $ref: paths/login.yaml
  /signup:
    $ref: paths/signup.yaml
  /me:
    $ref: paths/me.yaml
components:
  securitySchemes:
    JWT:
      description: JWT bearer token description...
      type: http
      scheme: bearer
      bearerFormat: JWT
